package com.alpacaflow.meditrack.devices.devices.domain.model.aggregates;


import com.alpacaflow.meditrack.devices.devices.domain.model.commands.CreateAlertCommand;
import com.alpacaflow.meditrack.devices.devices.domain.model.valueobjects.EAlertType;
import com.alpacaflow.meditrack.devices.devices.domain.model.valueobjects.EThresholdViolation;
import com.alpacaflow.meditrack.devices.shared.domain.model.aggregates.AuditableAbstractAggregateRoot;
import jakarta.persistence.*;
import lombok.Getter;
import org.apache.logging.log4j.util.Strings;

import java.time.LocalDateTime;

/**
 * Alert aggregate root
 * @summary
 * This aggregate root represents an alert generated by a device.
 * An alert is triggered when a measurement exceeds safe thresholds.
 * @since 1.0
 */
@Getter
@Entity
public class Alert extends AuditableAbstractAggregateRoot<Alert> {
    @Column(nullable = false)
    private Long deviceId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EAlertType alertType;

    @Column(nullable = false)
    private String message;

    @Column(nullable = false)
    private double dataRegistered;

    @Column(nullable = false)
    private LocalDateTime registeredAt;

    public Alert() {
        this.message = Strings.EMPTY;
        this.registeredAt = LocalDateTime.now();
    }

    /**
     * Create a new alert
     * @param deviceId The device ID that generated the alert
     * @param dataRegistered The measurement value that triggered the alert
     * @param measurementType The type of measurement
     * @param violation Direction of the threshold breach, when applicable
     */
    public Alert(Long deviceId, double dataRegistered, String measurementType, EThresholdViolation violation) {
        this();
        this.deviceId = deviceId;
        this.dataRegistered = dataRegistered;
        this.alertType = EAlertType.DANGER;
        this.message = setMessage(measurementType, violation);
        this.registeredAt = LocalDateTime.now();
    }

    /**
     * Create a new alert with information from the command
     * @param command The command to create the alert
     * @see CreateAlertCommand
     */
    public Alert(CreateAlertCommand command) {
        this(command.deviceId(), command.dataRegistered(), command.measurementType(), command.violation());
    }

    /**
     * Prefix used to deduplicate repeated alerts of the same kind within a cooldown window.
     */
    public static String dedupePrefix(String measurementType, EThresholdViolation violation) {
        return switch (measurementType.toUpperCase()) {
            case "TEMPERATURE" -> violation == EThresholdViolation.LOW
                    ? "Low temperature recorded:"
                    : "High temperature recorded:";
            case "HEARTRATE", "HEART_RATE" -> violation == EThresholdViolation.LOW
                    ? "Low heart rate recorded:"
                    : "High heart rate recorded:";
            case "OXYGEN" -> "Low oxygen saturation recorded:";
            case "BLOODPRESSURE", "BLOOD_PRESSURE" -> "Abnormal blood pressure recorded:";
            default -> "Unknown measurement type";
        };
    }

    /**
     * Set the alert message based on measurement type and violation direction
     * @param measurementType The type of measurement
     * @param violation Direction of the threshold breach, when applicable
     * @return The formatted message
     */
    private String setMessage(String measurementType, EThresholdViolation violation) {
        return setMessage(measurementType, violation, dataRegistered);
    }

    private static String setMessage(String measurementType, EThresholdViolation violation, double value) {
        return switch (measurementType.toUpperCase()) {
            case "TEMPERATURE" -> violation == EThresholdViolation.LOW
                    ? String.format("Low temperature recorded: %.2f°C", value)
                    : String.format("High temperature recorded: %.2f°C", value);
            case "HEARTRATE", "HEART_RATE" -> violation == EThresholdViolation.LOW
                    ? String.format("Low heart rate recorded: %.0f bpm", value)
                    : String.format("High heart rate recorded: %.0f bpm", value);
            case "OXYGEN" -> String.format("Low oxygen saturation recorded: %.0f%%", value);
            case "BLOODPRESSURE", "BLOOD_PRESSURE" -> String.format("Abnormal blood pressure recorded: %.0f mmHg", value);
            default -> "Unknown measurement type";
        };
    }
}
